### ISSUE TITLE
Something Wrong with the Giant Fibre Neuron

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/VFB#586]
won't open on existing or new system.

I'm investigating...

Support info:
http://www.virtualflybrain.org/site/tools/anatomy_finder/index.htm?id=FBbt:00004020&name=giant%20fiber%20neuron
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.130 Safari/537.36

**Comment by Robbie1977** [comment]
GO term resolution causing infinite loop - resolved in new build and hotfix applied to current site.

**Comment by dosumis** [comment]
Still don't understand the problem.  If GO term showing, does that mean you're using the full version (with inds) for metadata, rather than the -simple one?

**Comment by Robbie1977** [comment]
This was an issue with the regex adding links to the GO refs - it's fixed
although since IT have decided Java 1.7 is no longer safe we have some
issues with bocian (preventing testing of the fix) that have been keeping
me busy. I've stopped any upgrades (1.7 removal) on blanik and karenin
until I can get everything working with 1.8 on bocian.
