### ISSUE TITLE
Error page from neuron type on dev

### ISSUE THREAD

**Issue by mmc46** [VirtualFlyBrain/VFB#694]
Don't know if there's something being update in dev, but getting to this page clicking on any neuron type from the results here

hhttp://vfbdev.inf.ed.ac.uk/do/ont_bean_list.html?action=synaptic&id=FBbt:00003982

shows the error page

Support info:
http://vfbdev.inf.ed.ac.uk/do/ont_bean_list.html?action=synaptic&id=FBbt:00003982
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36 Size:[1573,1447]
!M561.0!e2eZ!e8e0!M1511,255,108!E!B!11!c39c2!c36c3!j1!F313!4e!L0340041!G!H2!2S!20!2i!6!H2!F5!G!H3!2S!20!2i!6!H3!F5!G!P3!0

![error_page](https://cloud.githubusercontent.com/assets/1872083/9785733/599c0d08-57ac-11e5-9ae5-6bb663c46cbb.png)

This neuron type is one of the ids that was going to be added from #691.

**Comment by mmc46** [comment]
This is also happening with any results here

http://vfbdev.inf.ed.ac.uk/do/ont_bean_list.html?action=lineage_clone&id=FBbt:00045048

**Comment by mmc46** [comment]
Any chance of getting this fixed soon @Robbie1977 ? This is making the results page pretty unusable in terms of getting to the term info page.

**Comment by Robbie1977** [comment]
I'm notting getting any error on either of these pages are you sure it's not a chached version from when the DB was faulty?

**Comment by Robbie1977** [comment]
If you right click and 'inspect element' and then in network tab tick 'no cache' it should pull the current page

**Comment by mmc46** [comment]
Still getting it on dev and sandbox 3, after clearing the cache, chrome and firefox.

I'm testing the results from example query 2.

http://vfbdev.inf.ed.ac.uk/do/ont_bean_list.html?action=synaptic&id=FBbt:00003982

Something else is going on a the moment as well, though, it wasn't happening before, so not sure it's related. The images in home aren't loading, and the results page also doesn't completely load (images don't show up).
The console from Inspect element on Firefox says

The stylesheet http://vfbdev.inf.ed.ac.uk/do/ont_bean_list.html?action=synaptic&id=FBbt:00003982 was not loaded because its MIME type, "text/html", is not "text/css". ont_bean_list.html
SyntaxError: expected expression, got '<' ont_bean_list.html:10:0
TypeError: parent.$(...).data(...) is undefined

**Comment by Robbie1977** [comment]
I get the same CSS error but the page loads fine in firefox, safari and chrome. can you try a different machine?
Found an error when starting from scratch (when testing on new machine) but don't think that's what your getting

**Comment by Robbie1977** [comment]
Now I think I've got it:
http://vfbdev.inf.ed.ac.uk/site/tools/anatomy_finder/?id=FBbt_00110633
Investigating...

**Comment by Robbie1977** [comment]
Should now be fixed on dev - if you're happy I can push onto Sandbox3

**Comment by Robbie1977** [comment]
Sorry it took me so long to figure out which page was actually failing.

**Comment by mmc46** [comment]
The page is now loading ok on dev

http://vfbdev.inf.ed.ac.uk/do/ont_bean_list.html?action=synaptic&id=FBbt:00003982

But clicking on any 'Name' on this results page still shows me the error page. 

I've got the tick on 'disable cache' in Network on Inspect element.

**Comment by Robbie1977** [comment]
what is the url it tries to open?

**Comment by mmc46** [comment]
It's now working on Chrome as well, I don't get an error page anymore for any of the results rows.

**Comment by Robbie1977** [comment]
good
