### ISSUE TITLE
Term info stays below viewer

### ISSUE THREAD

**Issue by mmc46** [VirtualFlyBrain/VFB#726]
The term info stays stays below the viewer, instead of on the right.
The zoom has also become unresponsive.

![term_info](https://cloud.githubusercontent.com/assets/1872083/10246715/8f048b3a-690b-11e5-8890-c97e0bd9d185.png)

Support info:
http://vfbdev.inf.ed.ac.uk/site/stacks/index.htm?add=VFBt_00100000
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36 Size:[1276,679]
!M570.9!M4!6Z!e8e0!M1511,255,108!E!B!G!H2!2S!20!2i!6!H2!F5!G!H3!2S!20!2i!6!H3!F5!G!P3!0

**Comment by Robbie1977** [comment]
It's the page width being below 1280 that's the min width I set to support side by side support without one overlapping the other.

I could remove the restriction all together:
![image](https://cloud.githubusercontent.com/assets/4630768/10246926/1ed4d494-690d-11e5-9354-7c6c08aecf37.png)
But as you can see we do get overlap.

I've reduced the min width to what I think is the bare minimum see what you think.

**Comment by mmc46** [comment]
It's now on the right. But the zoom is still unresponsive, not changing from 0.9. even when moving the slider. So I can't see any overlap. Is this expected behaviour?

I can move the slider, but nothing happens, and the slider keeps going back to 0.9 on its own.

**Comment by Robbie1977** [comment]
Shouldn't do that: 
do you have more than one window open?
Which browser is this in?

**Comment by mmc46** [comment]
I have 2 windows, but only one on the viewer. 
On Chrome Version 45.0.2454.101 (64-bit)

**Comment by Robbie1977** [comment]
just open the dev / inspect element window and see if the console log is showing anything when this happens - I suspect the settings on the other page are overriding.

Will fix...

**Comment by mmc46** [comment]
The console doesn't show anything.

**Comment by Robbie1977** [comment]
should be giving 'loading slice #' messages if nothing else

**Comment by Robbie1977** [comment]
should be fixed now

**Comment by mmc46** [comment]
Still happening for me, after clearing the cache. The console doesn't show anything when changing the zoom or loving slices.
But if I click on the viewer frame border, so where the cursor turns onto a +, but outside the black background I get

overridden by another session
3wlziip.js:1861 Uncaught TypeError: Cannot read property 'indexOf' of undefinedaddAvailableItems @ wlziip.js:1861$.ajax.success @ wlziip.js:631m.Callbacks.j @ jquery-1.11.3.min.js:2m.Callbacks.k.fireWith @ jquery-1.11.3.min.js:2x @ jquery-1.11.3.min.js:5m.ajaxTransport.a.send.b @ jquery-1.11.3.min.js:5

I don't have any other windows open.

**Comment by Robbie1977** [comment]
The error is just due to a empty response - should be handled without error now.
There maybe an overridden message when the page loads as it's GUID will change each load so it is overridden by itself on first load.

**Comment by Robbie1977** [comment]
Which Browser are you testing in?

**Comment by mmc46** [comment]
Chrome, version in previous comment. 

Marta

**Comment by Robbie1977** [comment]
Try it now - there was a fault (double double quotes) in the meta json file for the main template after I removed the obsolete term. This resulted in no meta data being loaded and scaling etc going off.
